# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nicolas/Documents/perso/strava_application

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nicolas/Documents/perso/strava_application

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nicolas/Documents/perso/strava_application/CMakeFiles /home/nicolas/Documents/perso/strava_application//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nicolas/Documents/perso/strava_application/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named strava

# Build rule for target.
strava: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 strava
.PHONY : strava

# fast build rule for target.
strava/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/build
.PHONY : strava/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/main.cpp.s
.PHONY : main.cpp.s

src/Analyzer.o: src/Analyzer.cpp.o
.PHONY : src/Analyzer.o

# target to build an object file
src/Analyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/Analyzer.cpp.o
.PHONY : src/Analyzer.cpp.o

src/Analyzer.i: src/Analyzer.cpp.i
.PHONY : src/Analyzer.i

# target to preprocess a source file
src/Analyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/Analyzer.cpp.i
.PHONY : src/Analyzer.cpp.i

src/Analyzer.s: src/Analyzer.cpp.s
.PHONY : src/Analyzer.s

# target to generate assembly for a file
src/Analyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/Analyzer.cpp.s
.PHONY : src/Analyzer.cpp.s

src/Connector.o: src/Connector.cpp.o
.PHONY : src/Connector.o

# target to build an object file
src/Connector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/Connector.cpp.o
.PHONY : src/Connector.cpp.o

src/Connector.i: src/Connector.cpp.i
.PHONY : src/Connector.i

# target to preprocess a source file
src/Connector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/Connector.cpp.i
.PHONY : src/Connector.cpp.i

src/Connector.s: src/Connector.cpp.s
.PHONY : src/Connector.s

# target to generate assembly for a file
src/Connector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/Connector.cpp.s
.PHONY : src/Connector.cpp.s

src/Logger.o: src/Logger.cpp.o
.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i
.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s
.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/StravaAuthController.o: src/StravaAuthController.cpp.o
.PHONY : src/StravaAuthController.o

# target to build an object file
src/StravaAuthController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/StravaAuthController.cpp.o
.PHONY : src/StravaAuthController.cpp.o

src/StravaAuthController.i: src/StravaAuthController.cpp.i
.PHONY : src/StravaAuthController.i

# target to preprocess a source file
src/StravaAuthController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/StravaAuthController.cpp.i
.PHONY : src/StravaAuthController.cpp.i

src/StravaAuthController.s: src/StravaAuthController.cpp.s
.PHONY : src/StravaAuthController.s

# target to generate assembly for a file
src/StravaAuthController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/StravaAuthController.cpp.s
.PHONY : src/StravaAuthController.cpp.s

src/csvParser.o: src/csvParser.cpp.o
.PHONY : src/csvParser.o

# target to build an object file
src/csvParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/csvParser.cpp.o
.PHONY : src/csvParser.cpp.o

src/csvParser.i: src/csvParser.cpp.i
.PHONY : src/csvParser.i

# target to preprocess a source file
src/csvParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/csvParser.cpp.i
.PHONY : src/csvParser.cpp.i

src/csvParser.s: src/csvParser.cpp.s
.PHONY : src/csvParser.s

# target to generate assembly for a file
src/csvParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strava.dir/build.make CMakeFiles/strava.dir/src/csvParser.cpp.s
.PHONY : src/csvParser.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... strava"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Analyzer.o"
	@echo "... src/Analyzer.i"
	@echo "... src/Analyzer.s"
	@echo "... src/Connector.o"
	@echo "... src/Connector.i"
	@echo "... src/Connector.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/StravaAuthController.o"
	@echo "... src/StravaAuthController.i"
	@echo "... src/StravaAuthController.s"
	@echo "... src/csvParser.o"
	@echo "... src/csvParser.i"
	@echo "... src/csvParser.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

